name: Publish Docker image
on:
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: sigidoc/sigidoc_latest
          tags: latest
          dockerfile: Dockerfile
  deploy:
    name: Deploy image
    needs: push_to_registry
    runs-on: self-hosted
    steps:
      - name: Pull image
        run: docker pull ghcr.io/sigidoc/sigidoc_latest:latest
      - name: Stop previous container
        run: docker stop sigidoc || true && docker rm sigidoc || true
      - name: Run image
        run: docker run -p 9000:9999 -d --rm --name sigidoc ghcr.io/sigidoc/sigidoc_latest:latest
  process_data:
    name: Process data
    needs: deploy
    runs-on: self-hosted
    steps:
      - name: Create Kiln repository
        run: docker exec sigidoc /bin/bash /sigidoc/scripts/create-kiln.sh
      - name: Harvest RDFS
        run: docker exec sigidoc /bin/bash /sigidoc/scripts/harvest-rdfs.sh
      - name: Index ALL
        run: docker exec sigidoc /bin/bash /sigidoc/scripts/index-all.sh
